import React from 'react'
import Head from 'next/head'
import Login from './LoginView'

export default function LoginContainer() {
  return (
    <>
      <Head>
        <title>Login | Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </>
  )
}
