import React from 'react'
import Head from 'next/head'
import Home from './home'

export default function HomeContainer() {
  return (
    <>
      <Head>
        <title>Home | Front-end</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  )
}
