import React, { useEffect } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import {
  usePositions
} from 'store'

import JobsId from './JobsIdView'
import cloneDeep from 'lodash.clonedeep'

export default function JobsIdContainer() {
  const router = useRouter()
  const {
    query: {
      id
    }
  }: any = router
  let jobsState = usePositions((state: any) => state.jobs)
  let setJobsLoading = usePositions((state: any) => state.jobs.setJobsLoading)
  let getJobsDetail = usePositions((state: any) => state.jobs.getJobsDetail)
  const jobs = cloneDeep(jobsState)
  const {
    query,
    isLoading
  } = jobs
  useEffect(() => {
    if (!isLoading && query && id) {
      setJobsLoading()
      getJobsDetail(id)
    }
  }, [])
  const handler = {
    ...jobs
  }
  return (
    <>
      <Head>
        <title>Jobs | Front-end</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <JobsId 
        {...handler}
      />
    </>
  )
}
