/* LAYOUT */
export const AUTH_SET_LOGIN = "AUTH/SET_LOGIN"
export const AUTH_SET_LOGIN_LOADING = "AUTH/SET_LOGIN_LOADING"
export const AUTH_SET_LOGIN_RESET = "AUTH/SET_LOGIN_RESET"
export const AUTH_SET_LOGIN_SUCCESS = "AUTH/SET_LOGIN_SUCCESS"
export const AUTH_SET_LOGIN_FAILURE = "AUTH/SET_LOGIN_FAILURE"
export const AUTH_SET_LOGOUT = "AUTH/SET_LOGOUT"
export const AUTH_SET_REGISTRATION = "AUTH/SET_REGISTRATION"
export const AUTH_SET_PASSWORD = "AUTH/SET_PASSWORD"
